exercise: exercise.c
	cc exercise.c -o exercise

fig3-1: fig3-1.c
	cc fig3-1.c -o fig3-1

fig3-2: fig3-2.c
	cc fig3-2.c -o fig3-2

fig3-3: fig3-3.c
	cc fig3-3.c -o fig3-3

fig3-4: fig3-4.c
	cc fig3-4.c -o fig3-4

fig3-5: fig3-5.c
	cc fig3-5.c -o fig3-5

fig3-6: fig3-6.c
	cc fig3-6.c -o fig3-6

fig3-7: fig3-7.c
	cc fig3-7.c -o fig3-7

fig3-8: fig3-8.c
	cc fig3-8.c -o fig3-8

fig3-9: fig3-9.c
	cc fig3-9.c -o fig3-9

fig3-10: fig3-10.c
	cc fig3-10.c -o fig3-10

fig3-11: fig3-11.c
	cc fig3-11.c -o fig3-11

fig3-12: fig3-12.c
	cc fig3-12.c -o fig3-12

fig4-5: fig4-5.c
	cc fig4-5.c -o fig4-5

fig4-6: fig4-6.c
	cc fig4-6.c -o fig4-6

fig4-7: fig4-7.c
	cc fig4-7.c -o fig4-7

fig4-8: fig4-8.c
	cc fig4-8.c -o fig4-8
